# serverless.yml

service: invrtir-grafico-lineal-cripto-lp
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: proy
  region: us-east-2
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_USER: ${env:DB_USER}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_PORT: ${env:DB_PORT}
    DB_DATABASE: ${env:DB_DATABASE}
    TABLE_CRIPTO_PRECIO_ACTUAL: ${env:TABLE_CRIPTO_PRECIO_ACTUAL}
    TABLE_CRIPTO_PROY_LP: ${env:TABLE_CRIPTO_PROY_LP}

functions:
  app:
    handler: index.handler
    description: LCG3 - Obtiene el gr√°fico de Proyecciones a largo plazo de Criptos desde los datos de AWS RDS.
    events:
      - http: GET /
      - http: 'GET {proxy+}'
